name: downloadsfolder
description: A Flutter plugin for retrieving the path to the downloads folder and performing operations related to file downloads on different platforms.
version: 1.2.0
homepage: https://github.com/UnluckyY1
repository: https://github.com/UnluckyY1/flutter_downloads_folder

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  path_provider: ^2.1.5
  path: ^1.9.0
  diacritic: ^0.1.6
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.oodrive.downloadsfolder
        pluginClass: DownloadsfolderPlugin
      ios:
        pluginClass: DownloadsfolderPlugin
      #linux:  TODO find away to show the linux tag on pub.dev
      macos:
        pluginClass: DownloadsfolderPlugin
      windows:
        pluginClass: DownloadsfolderPluginCApi

